apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: multi-tenancy-gitops
    group: pipeline
    type: git
  name: gitops-repo
data:
  branch: master
  host: github.com
  org: personal-mq-cluster
  owner: personal-mq-cluster
  parentdir: .
  protocol: https
  repo: multi-tenancy-gitops-apps
  url: https://github.com/personal-mq-cluster/multi-tenancy-gitops-apps.git
